version: '3'

services:
    workers:
        build: ./broker
        container_name: broker
        restart: always
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

networks:
    default:
        external:
            name: rede