version: '3'

services:
    workers:
        build: ./broker
        ports:
          - 5001:5001
        container_name: broker
        restart: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

networks:
    default:
        external:
            name: rede
